version: '3'
services:
  web:
    image: 585172581592.dkr.ecr.ap-southeast-2.amazonaws.com/vly1-main-repo:latest
    depends_on:
      - db
    ports:
      - "${WEB_PORT:-80}:8000"
    environment:
      NODE_ENV: production
      MONGO_URL: MONGO_URL: mongodb://db:27017/vly-dev
  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - dbdata:/data/db
volumes:
  dbdata:
