version: '3'
services:
  web:
    image: 585172581592.dkr.ecr.ap-southeast-2.amazonaws.com/vly2-main-repo:latest
    ports:
      - "${WEB_PORT:-80}:8000"
    environment:
      NODE_ENV: production
      MONGO_URL: mongodb+srv://vly-client:ZhF3BUDiwpy8C3xK@cluster0-kwmsu.mongodb.net/vly2-prod?retryWrites=true

