# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
# Author: Andrew Somervell

name: V2LY

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lang:    
    name: Lang
    runs-on: ubuntu-latest
    steps:
    - name: Check out
      uses: actions/checkout@v2      
    - name: Use Node 12
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Lang
      run: |
        npm ci
        cp lang/en.json lang/en.orig.json
        npm run build:lang
        diff lang/en.json lang/en.orig.json
      
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - name: Check out
      uses: actions/checkout@v2      
    - name: Use Node 12
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Lint
      run: |
        npm ci
        npm run lint
    
  test:
    name: NPM and System Test
    runs-on: ubuntu-latest
    needs: [lang, lint]
    steps:
    - name: Check out
      uses: actions/checkout@v2      
    - name: Use Node 12
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
        mongoms_download_mirror: http://downloads.mongodb.org
        mongoms_version: 4.0.5
        mongoms_disable_postinstall: 1
        ci_node_index: 0
        ci_node_total: 1
        codecov_token: ${{ secrets.CODECOV_TOKEN }}

    - name: NPM Test          
      run: |
        npm ci
        npm run test-all -- --tap
        
    - name: Code coverage          
      run: |       
        ./node_modules/codecov/bin/codecov --disable=gcov
        
    - name: System Test
      run: |
        apt-get update
        apt-get install -y firefox-esr
        npm run end-to-end-test

  docker-build:
    name: Build and push docker container
    runs-on: ubuntu-latest
    needs: [test, lint]
    steps:
    - name: Install AWS CLI          
      run: |
        pip install awscli
        wget https://s3.amazonaws.com/amazon-ecs-cli/ecs-cli-linux-amd64-latest -O ./ecs-cli
        chmod +x ./ecs-cli
        mv ./ecs-cli /usr/local/bin/
        which ecs-cli        
    - name: build
      run: ./x/aws/buildimage
    - name: deploy
      run: ./x/aws/deploy-alpha
  
      env:
        AWS_ACCOUNT_ID: 585172581592
        AWS_ACCESS_KEY_ID: AKIAYQPYA7TMKZS4NM6W
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ap-southeast-2
        BADGR_USERNAME: andrew+badgr@voluntarily.nz
        BADGR_PASSWORD: ${{ secrets.BADGR_PASSWORD }}
        SMTP_ID: ${{ secrets.SMTP_ID }} 
        SMTP_PWD: ${{ secrets.SMTP_PWD }}
        VLY_PRIVATE_KEY: ${{ secrets.VLY_PRIVATE_KEY }}
        IMAGE_TAG_VERSION: GITHUB_SHA
        HOME: /root
        APP_URL: https://alpha.voluntarily.nz
        RAYGUN_EXPRESS_SERVER_API_KEY: ${{ secrets.RAYGUN_EXPRESS_SERVER_API_KEY }}
        RAYGUN_REACT_CLIENT_API_KEY: ${{ secrets.RAYGUN_REACT_CLIENT_API_KEY }}
