
name: V2LY PR

on:
  pull_request:
    branches:
      - master

jobs:
              
  component:
    name: Full tests and coverage
    runs-on: self-hosted
    steps:
    - name: Check out
      uses: actions/checkout@v2      
    - name: Use Node 12
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
        mongoms_download_mirror: http://downloads.mongodb.org
        mongoms_version: 4.0.5
        mongoms_disable_postinstall: 1
        ci_node_index: 0
        ci_node_total: 1
    - name: Full Tests          
      run: |
        npm ci
        npx nyc --reporter=lcov --reporter=text ava
    - name: coverage
    - uses: codecov/codecov-action@v1 

  # integration:
  #   name: Integration Tests
  #   runs-on: self-hosted
  #   steps:
  #   - name: Check out
  #     uses: actions/checkout@v2      
  #   - name: Use Node 12
  #     uses: actions/setup-node@v1
  #     with:
  #     node-version: 12.x
  #     mongoms_download_mirror: http://downloads.mongodb.org
  #     mongoms_version: 4.0.5
  #     mongoms_disable_postinstall: 1
  #     ci_node_index: 0
  #     ci_node_total: 1
  #   - name: Integration Tests          
  #     run: |
  #       npm ci
  #       npx nyc --reporter=lcov --reporter=text ava
